import React, { useEffect, useMemo, useState } from 'react';
import './styles.css';
import { createRoot } from 'react-dom/client';
import { Analytics } from '@vercel/analytics/react';
import { createVisionProvider } from './services/vision.js';
import { validateProfile } from './services/safety.js';
import { createMealFromAnalysis, updateMealItem } from './services/meal.js';
import { storage } from './services/storage.js';
import { summarizeDay } from './services/analytics.js';
import { trackEvent, EVENTS } from './services/tracking.js';
import { getDailyGuide } from './data/dailyGuide.js';

const defaultProfile = { name: '', age: '', weight: '', height: '', goal: 'bienestar', activity: 'moderada', conditions: '' };
const TRIAL_MS = 24 * 60 * 60 * 1000;
const visionProvider = createVisionProvider();
function trialStatus(trial) { if (!trial?.startedAt) return { active:false, expired:false, remaining:0 }; const remaining = TRIAL_MS - (Date.now() - new Date(trial.startedAt).getTime()); return { active:remaining>0, expired:remaining<=0, remaining:Math.max(0,remaining) }; }

function App() {
  const [trial,setTrial]=useState(()=>storage.getTrial()); const [profile,setProfile]=useState(()=>storage.getProfile()||defaultProfile); const [meals,setMeals]=useState(()=>storage.getMeals()); const [activities,setActivities]=useState(()=>storage.getActivity()); const [view,setView]=useState('inicio'); const [photo,setPhoto]=useState(null); const [analysis,setAnalysis]=useState(null); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false); const [now,setNow]=useState(Date.now()); const [plusInterest,setPlusInterest]=useState(false);
  const [currentDay,setCurrentDay]=useState(()=>Math.min(7,Math.max(1,Number(localStorage.getItem('nutrifoto-current-day')||1))));
  const status=useMemo(()=>trialStatus(trial),[trial,now]); const today=useMemo(()=>summarizeDay(meals,activities),[meals,activities]); const guide=getDailyGuide(currentDay,profile.goal);
  useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(t)},[]); useEffect(()=>{localStorage.setItem('nutrifoto-current-day',String(currentDay))},[currentDay]); useEffect(()=>{if(notice){const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t)}},[notice]);
  useEffect(()=>{if(trial?.startedAt&&view==='inicio'&&status.active)trackEvent(EVENTS.guideOpened)},[view,currentDay,trial?.startedAt,status.active]);
  useEffect(()=>{if(trial?.startedAt&&status.expired){trackEvent(EVENTS.trialFinished);trackEvent(EVENTS.plusViewed)}},[trial?.startedAt,status.expired]);
  function startTrial(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());const age=Number(data.age);if(!data.name?.trim())return setNotice('Ingresá tu nombre.');if(!/^\S+@\S+\.\S+$/.test(data.email||''))return setNotice('Ingresá un email válido.');if(!Number.isFinite(age)||age<18)return setNotice('La prueba está disponible para personas adultas.');const next=storage.startTrial({name:data.name.trim(),email:data.email.trim().toLowerCase(),age});const p={...profile,name:data.name.trim(),age:String(age)};storage.saveProfile(p);setProfile(p);setTrial(next);setCurrentDay(1);setView('inicio');trackEvent(EVENTS.trialStarted);setNotice('Tu prueba gratuita de 1 día comenzó.')}
  function requireActiveTrial(){if(!status.active){setView('final');return false}return true}
  function updateProfile(e){e.preventDefault();const next=Object.fromEntries(new FormData(e.currentTarget).entries());const safety=validateProfile(next);if(!safety.isAdult)return setNotice(safety.warnings[0]||'Ingresá una edad válida.');setProfile(next);storage.saveProfile(next);trackEvent(EVENTS.objectiveSelected);setNotice('Perfil guardado.')}
  function handlePhoto(e){if(!requireActiveTrial())return;const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return setNotice('Seleccioná una imagen.');if(file.size>8*1024*1024)return setNotice('La imagen debe pesar menos de 8 MB.');const reader=new FileReader();reader.onload=()=>setPhoto(reader.result);reader.readAsDataURL(file);setAnalysis(null);trackEvent(EVENTS.photoStarted)}
  async function analyzePhoto(){if(!requireActiveTrial())return;if(!photo)return setNotice('Primero cargá una foto.');setBusy(true);try{setAnalysis(await visionProvider.analyzeImage(photo))}catch(error){setNotice(error.message||'No se pudo analizar la imagen.')}finally{setBusy(false)}}
  function editItem(index,field,value){const numeric=['portionGrams','calories','protein','carbs','fat'].includes(field);setAnalysis(a=>updateMealItem({...a,items:a.items},index,{[field]:numeric?Number(value):value}))}
  function saveMeal(){if(!requireActiveTrial())return;try{const meal=createMealFromAnalysis(analysis);storage.saveMeal(meal);setMeals(storage.getMeals());trackEvent(EVENTS.mealRegistered);setNotice('Comida registrada.');setAnalysis(null);setPhoto(null);setView('registro')}catch{setNotice('Revisá el resultado antes de guardar.')}}
  function addActivity(e){e.preventDefault();if(!requireActiveTrial())return;const form=Object.fromEntries(new FormData(e.currentTarget).entries());storage.saveActivity({id:crypto.randomUUID(),date:new Date().toISOString(),activity:form.activity,durationMinutes:Number(form.minutes)});setActivities(storage.getActivity());e.currentTarget.reset();setNotice('Actividad registrada.')}
  function deleteAllLocalData(){if(!window.confirm('Esto eliminará el perfil, comidas, actividad y prueba guardados en este dispositivo. ¿Continuar?'))return;storage.clearAll();localStorage.removeItem('nutrifoto-current-day');setTrial(null);setProfile(defaultProfile);setMeals([]);setActivities([]);setAnalysis(null);setPhoto(null);setCurrentDay(1);setView('inicio');setNotice('Tus datos locales fueron eliminados.')}
  function showPlusInterest(){trackEvent(EVENTS.plusInterest);setPlusInterest(true)}
  function nextDay(){if(!requireActiveTrial())return;if(currentDay<7){setCurrentDay(currentDay+1);setView('inicio');trackEvent(EVENTS.nextDay);setNotice(`Pasaste al Día ${currentDay+1} de 7.`)}else setNotice('Completaste los 7 días de la guía.')} function previousDay(){if(currentDay>1)setCurrentDay(currentDay-1)}
  const demo=analysis?.isDemo===true; const hoursLeft=Math.ceil(status.remaining/(60*60*1000));
  if(!trial)return <div className="app"><main><section className="page narrow trial-page"><span className="eyebrow">NUTRIFOTO</span><h1>Probá Nutrifoto<br/><em>gratis durante 1 día.</em></h1><p className="lead">Registrá tus comidas, probá el recorrido de fotografía y conocé tu resumen diario.</p><form className="profile trial-form" onSubmit={startTrial}><label>Nombre<input name="name" autoComplete="name" required placeholder="Tu nombre"/></label><label>Email<input name="email" type="email" autoComplete="email" required placeholder="tu@email.com"/></label><label>Edad<input name="age" type="number" min="18" max="120" required placeholder="18 o más"/></label><button className="primary wide">Empezar mi prueba gratis</button></form><p className="warning">La prueba actual funciona en este dispositivo. Para una cuenta sincronizada entre dispositivos necesitaremos incorporar un servicio de cuentas más adelante.</p></section></main><footer>Nutrifoto · Las estimaciones nutricionales son orientativas.</footer></div>;
  if(status.expired)return <div className="app"><main><section className="page narrow trial-page"><span className="eyebrow">TU PRUEBA FINALIZÓ</span><h1>¿Querés seguir<br/><em>con Nutrifoto?</em></h1><p className="lead">Gracias por probar la app, {trial.name}. Si te resultó útil, podés dejar registrada tu intención de continuar. El cobro todavía no está habilitado.</p><div className="plus-card"><span className="eyebrow">NUTRIFOTO PLUS</span><h2>Más herramientas para organizar tus hábitos</h2><ul><li>Guía y planificación semanal</li><li>Registro e historial de comidas</li><li>Seguimiento de hábitos, movimiento e hidratación</li><li>Lista de compras y más recursos</li></ul><div className="plus-prices"><div><strong>USD 4,99</strong><span>por mes</span></div><div><strong>USD 39,90</strong><span>por año</span></div></div>{plusInterest?<div className="plus-success" role="status"><strong>¡Listo!</strong><span>Registramos tu interés. Todavía no se realizará ningún cobro.</span></div>:<button className="primary wide" onClick={showPlusInterest}>Me interesa Nutrifoto Plus</button>}</div><button className="secondary wide" onClick={()=>setPlusInterest(false)}>Continuar más tarde</button><button className="danger" onClick={deleteAllLocalData}>Eliminar mis datos de este dispositivo</button><p className="warning">Nutrifoto no reemplaza la evaluación de profesionales de la salud. Las estimaciones son orientativas.</p></section></main><footer>Nutrifoto · Sin cobros activos en esta etapa.</footer></div>;
  return <div className="app"><header className="topbar"><button className="brand" onClick={()=>setView('inicio')}><span className="brand-mark">N</span><span>Nutrifoto</span></button><nav>{[['inicio','Inicio'],['foto','Analizar foto'],['registro','Mi día'],['perfil','Mi perfil']].map(([id,label])=><button className={view===id?'active':''} key={id} onClick={()=>status.active?setView(id):setView('final')}>{label}</button>)}</nav></header>{notice&&<div className="notice">{notice}</div>}<main>
    {view==='inicio'&&<><section className="hero"><div><span className="eyebrow">PRUEBA GRATUITA · {hoursLeft} H RESTANTES</span><h1>Entendé mejor<br/><em>lo que comés.</em></h1><p>Una guía diaria para organizar tus comidas, registrar lo que comés y sumar movimiento.</p><button className="primary" onClick={()=>setView('foto')}>Registrar mi comida →</button></div><div className="hero-card"><div className="ring">N</div><strong>Tu día, de un vistazo</strong><div className="metric"><span>Calorías registradas</span><b>{Math.round(today.calories)}</b><small>kcal estimadas</small></div><div className="progress"><span style={{width:`${Math.min(today.calories/20,100)}%`}}/></div><div className="mini-grid"><div><b>{today.mealCount}</b><small>comidas</small></div><div><b>{today.activityMinutes}</b><small>min actividad</small></div></div></div></section><section className="day-guide"><div className="section-head"><div><span className="eyebrow">TU GUÍA · DÍA {currentDay} DE 7</span><h2>{guide.title}</h2><p>{guide.goalText} {guide.focus}</p></div><div className="day-controls"><button className="secondary" onClick={previousDay} disabled={currentDay===1}>← Anterior</button><button className="primary" onClick={nextDay}>{currentDay===7?'Finalizar 7 días':'Siguiente día →'}</button></div></div><div className="meal-guide-grid">{guide.meals.map((meal,i)=><article className="guide-card" key={meal.type}><span>0{i+1}</span><h3>{meal.type}</h3><p>{meal.text}</p>{meal.options?.length>1&&<small>Alternativas disponibles</small>}<button onClick={()=>setView('foto')}>Registrar con foto →</button></article>)}</div><div className="movement-card"><div><span className="eyebrow">MOVIMIENTO</span><h3>Hoy</h3><p>{guide.movement}</p></div><div><span className="eyebrow">HIDRATACIÓN</span><p>{guide.hydration}</p></div></div></section><section className="trust"><strong>Hola, {trial.name}.</strong><span>La guía es orientativa y puede adaptarse a tus necesidades. Nutrifoto no reemplaza la evaluación de profesionales de la salud.</span></section></>}
    {view==='foto'&&<section className="page"><div className="section-head"><div><span className="eyebrow">REGISTRAR COMIDA</span><h2>¿Qué comiste?</h2><p>Subí una imagen para revisar una estimación y guardarla en tu día.</p></div></div><div className="photo-layout"><label className="dropzone">{photo?<img src={photo} alt="Comida cargada"/>:<><span className="camera">＋</span><strong>Elegir una foto</strong><small>También podés usar la cámara del celular</small></>}<input type="file" accept="image/*" capture="environment" onChange={handlePhoto}/></label><div className="analysis-panel">{analysis?<><span className="eyebrow">REVISÁ</span>{demo&&<div className="demo-note" role="status"><strong>Modo demostración</strong><span>Los valores son de ejemplo. Modificalos antes de guardarlos.</span></div>}{analysis.items.map((item,index)=><div className="food-item" key={`${item.name}-${index}`}><label>Alimento<input value={item.name} onChange={e=>editItem(index,'name',e.target.value)}/></label><label>Porción (g)<input type="number" min="0" value={item.portionGrams} onChange={e=>editItem(index,'portionGrams',e.target.value)}/></label><div className="nutri"><label><b>kcal</b><input type="number" min="0" value={item.calories} onChange={e=>editItem(index,'calories',e.target.value)}/></label><label><b>proteína</b><input type="number" min="0" value={item.protein} onChange={e=>editItem(index,'protein',e.target.value)}/></label><label><b>carbohidratos</b><input type="number" min="0" value={item.carbs} onChange={e=>editItem(index,'carbs',e.target.value)}/></label><label><b>grasas</b><input type="number" min="0" value={item.fat} onChange={e=>editItem(index,'fat',e.target.value)}/></label></div></div>)}<button className="primary full" onClick={saveMeal}>Guardar mi comida</button><p className="warning">Las estimaciones son orientativas y no constituyen diagnóstico ni indicación médica.</p></>:<><div className="empty"><span>✦</span><strong>{busy?'Procesando…':'Tu foto está lista'}</strong><p>{busy?'Preparando el resultado.':'Subí una imagen y tocá el botón para continuar.'}</p></div><button className="primary full" disabled={busy} onClick={analyzePhoto}>{busy?'Procesando…':'Continuar con mi foto'}</button></>}</div></div></section>}
    {view==='registro'&&<section className="page"><div className="section-head"><div><span className="eyebrow">MI DÍA · DÍA {currentDay} DE 7</span><h2>Tu día de hoy</h2><p>{guide.goalText} {guide.focus}</p></div><button className="primary" onClick={()=>setView('foto')}>+ Registrar comida</button></div><div className="summary-grid"><div><b>{Math.round(today.calories)}</b><small>kcal estimadas</small></div><div><b>{Math.round(today.protein)} g</b><small>proteína</small></div><div><b>{Math.round(today.carbs)} g</b><small>carbohidratos</small></div><div><b>{Math.round(today.fat)} g</b><small>grasas</small></div></div><div className="meal-guide-grid compact">{guide.meals.map((m,i)=><article className="guide-card" key={m.type}><span>0{i+1}</span><h3>{m.type}</h3><p>{m.text}</p><button onClick={()=>setView('foto')}>Registrar →</button></article>)}</div><div className="log-list">{meals.filter(m=>String(m.date).slice(0,10)===today.date).map(m=><article className="log" key={m.id}><div className="food-icon">◌</div><div><strong>{m.items?.map(i=>i.name).join(', ')||'Comida'}</strong><small>{new Date(m.date).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}</small></div><b>{Math.round(m.calories)} kcal</b></article>)}</div><div className="activity-card"><div><span className="eyebrow">ACTIVIDAD</span><h3>Registrar movimiento</h3></div><form onSubmit={addActivity}><input name="activity" placeholder="Ej. caminar" required/><input name="minutes" type="number" min="1" placeholder="Minutos" required/><button className="secondary">Guardar</button></form></div></section>}
    {view==='perfil'&&<section className="page narrow"><span className="eyebrow">PERSONALIZACIÓN</span><h2>Mi perfil</h2><p className="lead">Completá tus datos para personalizar la experiencia.</p><form className="profile" onSubmit={updateProfile}>{[['name','Nombre','text'],['age','Edad','number'],['weight','Peso (kg)','number'],['height','Altura (cm)','number']].map(([name,label,type])=><label key={name}>{label}<input name={name} type={type} defaultValue={profile[name]} min={type==='number'?0:undefined}/></label>)}<label>Objetivo<select name="goal" defaultValue={profile.goal}><option value="bienestar">Bienestar</option><option value="mantener">Mantener hábitos</option><option value="organizar">Organizar alimentación</option><option value="descenso">Descenso de peso orientativo</option></select></label><label>Actividad<select name="activity" defaultValue={profile.activity}><option>ligera</option><option>moderada</option><option>alta</option></select></label><label className="wide">Condiciones o información relevante<textarea name="conditions" defaultValue={profile.conditions} placeholder="Opcional. No ingreses información que no quieras almacenar."/></label><button className="primary wide">Guardar perfil</button></form><button className="danger" onClick={deleteAllLocalData}>Eliminar mis datos de este dispositivo</button><p className="warning">Nutrifoto no diagnostica, no prescribe medicamentos y no reemplaza la evaluación de profesionales de la salud.</p></section>}
    {view==='final'&&<section className="page narrow trial-page"><span className="eyebrow">PRUEBA FINALIZADA</span><h2>Tu prueba terminó</h2><p className="lead">Podemos usar tu opinión para decidir qué funciones incluir en la próxima versión.</p><button className="secondary wide" onClick={()=>setView('inicio')}>Volver al inicio</button></section>}
  </main><footer>Nutrifoto · Las estimaciones nutricionales son orientativas.</footer></div>;
}
createRoot(document.getElementById('root')).render(<><App /><Analytics /></>);
